services:
  - type: web
    name: inventory-management-system
    plan: free
    rootDir: InventoryManagementSystem
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
